### ISSUE TITLE
HTML convert over to Lua screens

### ISSUE THREAD

**Issue by wokka1** [1337joe/du-factory-inventory#2]
with release, they have disabled the html screens by default, we can turn them back on, but this isn't ideal.

Any chance this could be updated for Lua screens?

There are also a couple of warnings that fire off when you launch the board, about deprecated commands.

Thanks for the great scripts!

**Comment by 1337joe** [comment]
I can't promise quick progress on it since I don't get a lot of time to play (and the reset took out my factory and testing facility), but I've started updating my tools for 1.0 with the intent of fixing this.

**Comment by wokka1** [comment]
I understand Joe.  If you need some factory parts to help get started, let me know and I'll donate some to the cause.
